### ISSUE TITLE
webassembly error

### ISSUE THREAD

**Issue by thegenius** [oxalica/async-ffi#1]
when i try to compile your guest example with:
cargo build --target wasm32-unknown-unknown --release

I get this error:
.into_ffi()
   |      ^^^^^^^^ `(dyn FnMut() + 'static)` cannot be sent between threads safely

**Comment by oxalica** [comment]
Currently we requires `Future`s to be `Send`. wasm target is single threaded so some crates (like `async-std`) seem to switch to different non-Send implementation for `async fn`s on wasm.

Maybe we need to introduce `LocalFfiFuture` to wrap non-`Send` `Future`s.
