### ISSUE TITLE
`FutureExt`'s name clashes with `async_std`'s

### ISSUE THREAD

**Issue by marioortizmanero** [oxalica/async-ffi#17]
I'd understand if you don't want to implement this, but it'd be nice to rename `FutureExt` to something similar. It's also a thing in `async_std`, and if you want to import both you need to use `use x::FutureExt as _`. What about `FfiFutureExt`? Or maybe you don't think this is an issue?

**Comment by oxalica** [comment]
> `use x::FutureExt as _`

It *is* the indented usage, not a workaround, if you only use the trait method instead of the trait itself.

Anyway, you can also just use `use async_ffi::FutureExt as FfiFutureExt` now.
