### ISSUE TITLE
LocalFfiFuture macro

### ISSUE THREAD

**Issue by ShayBox** [oxalica/async-ffi#21]
It would be nice if there was a way to specify LocalFfiFuture with the `#[async_ffi]` macro like `#[async_ffi::local]`/`#[async_ffi(local)]` or something.

```rust
#[no_mangle]
#[allow(clippy::unnecessary_wraps)]
#[allow(clippy::needless_pass_by_value)]
extern "Rust" fn chat(
    mut chatbox: String,
    mut console: String,
    handle: Handle,
) -> LocalFfiFuture<Result<(String, String)>> {
    async move {
        let _enter = handle.enter();

        todo!()
    }
    .into_local_ffi()
}
```

```rust
#[async_ffi(local)] // Example
#[no_mangle]
#[allow(clippy::unnecessary_wraps)]
#[allow(clippy::needless_pass_by_value)]
async extern "Rust" fn chat(
    mut chatbox: String,
    mut console: String,
    handle: Handle,
) -> Result<(String, String)> {
    let _enter = handle.enter();

    todo!()
}
```

**Comment by oxalica** [comment]
The syntax is `#[async_ffi(?Send)]` to mimic [`#[async_trait(?Send)]`](https://docs.rs/async-trait/0.1.77/async_trait/#non-threadsafe-futures).

It is mentioned in the [documentation of `async_ffi` proc-macro](https://docs.rs/async-ffi-macros/0.5.0/async_ffi_macros/attr.async_ffi.html#non-send-futures).

**Comment by ShayBox** [comment]
Oh, I didn't see that, thanks!
