### ISSUE TITLE
Handle panicking in "extern" fns more safely

### ISSUE THREAD

**Issue by Lej77** [oxalica/async-ffi#7]
I was looking through the source code of this crate after reading the article [Plugins in Rust: Reducing the Pain with Dependencies | NullDeref](https://nullderef.com/blog/plugin-abi-stable/) and I noticed that currently panicking is only handled for the [`LocalBorrowingFfiFuture::poll`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L404-L413) method and even that could be better since the `Box` that the is caught could panic when it is dropped, see [Footgun with `catch_unwind` when catching panic-on-drop types · Issue #86027 · rust-lang/rust](https://github.com/rust-lang/rust/issues/86027). This crate should probably do something similar to [the preposed `drop_unwind` fn](https://github.com/rust-lang/rust/pull/85927/files#diff-256489a401631296d6aebb6537ff78cde5cf3c0188004e6d2c479f7cbbc156d2R185-R195) or to [the `AbortBomb` in `abi_stable`](https://github.com/rodrimati1992/abi_stable_crates/blob/dae5ba3f2a9eb135a04290f2e0b2f967ee21e31f/abi_stable/src/utils.rs#L68-L76).

All of the following `extern "C"` functions should probably handle panics since they call arbitrary user provided functions:
- [`LocalBorrowingFfiFuture::drop`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L417-L419)
- [`LocalBorrowingFfiFuture::poll`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L398-L415) (currently handled except for caught panic payloads that panic when dropped)
- [`FfiWaker(reference)::wake_by_ref`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L211-L213)
- [`FfiWaker(reference)::clone`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L201-L210)
- [`FfiWaker(owned)::drop`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L187-L191)
- [`FfiWaker(owned)::wake_by_ref`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L183-L185)
- [`FfiWaker(owned)::wake`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L179-L182)
- [`FfiWaker(owned)::clone`](https://github.com/oxalica/async-ffi/blob/65bc54b4696281ffb48fd880046ec1d7da0a0652/src/lib.rs#L167-L176)

**Comment by Lej77** [comment]
The new code looks good and I can't find any safety issues with it.

I do think that the abort message should be `Waker::clone` and not `Waker::drop` at [line 194](https://github.com/oxalica/async-ffi/blob/d33ef5a1b5d60c3e36a61e0b316063ed4cb806f4/src/lib.rs#L194) for the owned vtable clone method.

Also in the [`poll_fn`](https://github.com/oxalica/async-ffi/blob/d33ef5a1b5d60c3e36a61e0b316063ed4cb806f4/src/lib.rs#L436) function is there a reason to not call `Pin::new_unchecked` and `(*context_ptr).with_context` inside the `catch_unwind` closure (seems like that would be safer if that code was ever changed to introduce a panic somewhere even if they can't panic currently).

**Comment by oxalica** [comment]
> I do think that the abort message should be `Waker::clone` and not `Waker::drop` at [line 194](https://github.com/oxalica/async-ffi/blob/d33ef5a1b5d60c3e36a61e0b316063ed4cb806f4/src/lib.rs#L194) for the owned vtable clone method.
> 
> Also in the [`poll_fn`](https://github.com/oxalica/async-ffi/blob/d33ef5a1b5d60c3e36a61e0b316063ed4cb806f4/src/lib.rs#L436) function, is there a reason to not call `Pin::new_unchecked` and `(*context_ptr).with_context` inside the `catch_unwind` closure (seems like that would be safer if that code was ever changed to introduce a panic somewhere even if they can't panic currently).

Thanks for the review. They are both fixed in https://github.com/oxalica/async-ffi/commit/b81ef7fd62d25348c31aea68016ed2fa3b8baae7 now. Documentations are also updated on master.
